{
 "title": "Mongodb Monitoring Dashboard - Final",
 "description": "MongoDB Dashboard using Mongodb Exporter for MongoDB deployed in Unix machines",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "env", "label": "Environment", "query": { "query": "label_values(environment)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(mongodb_up{environment=~\"$env\"},instance)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "database",
    "label": "database",
    "query": {
     "query": "label_values(mongodb_collstats_storageStats_totalSize{environment=\"$env\"},database)"
    }
   },
   {
    "name": "collection",
    "label": "collection",
    "query": {
     "query": "label_values(mongodb_collstats_storageStats_totalSize{database=~\"$database\"},collection)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "MongoDB on ${instance}",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (instance) (mongodb_up{environment=~\"$env\", instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MongoDB Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mongodb_version_info{instance=~\"$instance\"} or on(instance) mongodb_fcv_feature_compatibility_version{instance=~\"$instance\"}",
     "legendFormat": "{{mongodb}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "The parameter shows how long a system has been “up” and running without a shut down or restart.",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "node_time_seconds{environment=\"$env\", instance=~\"$instance\"} \r\n  - on(instance) \r\nnode_boot_time_seconds{environment=\"$env\", instance=~\"$instance\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU%",
   "type": "gauge",
   "description": "The CPU time is measured in clock ticks or seconds. It is useful to measure CPU time as a percentage of the CPU's capacity, which is called the CPU usage.",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", environment=\"$env\", instance=~\"$instance\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mem%",
   "type": "gauge",
   "description": "Estimated how much memory can be used without swapping",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (\r\n  1 - (\r\n    node_memory_MemAvailable_bytes{environment=\"$env\", instance=~\"$instance\"}\r\n    / on(instance) node_memory_MemTotal_bytes{environment=\"$env\", instance=~\"$instance\"}\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "description": "Network traffic refers to the amount of data moving across a network at a given point in time.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "sum(\r\n  rate(node_network_receive_bytes_total{environment=\"$env\", instance=~\"$instance\"}[$interval])\r\n  +\r\n  rate(node_network_transmit_bytes_total{environment=\"$env\", instance=~\"$instance\"}[$interval])\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Space Utilization",
   "type": "stat",
   "description": "Shows disk Utilization as a percentage of the time when there was at least one IO request in flight. It is designed to match utilization available in iostat tool. The graph augments the IO latency and Disk Load Graphs, allowing to determine if the disk load was evenly distributed in time or consuming the IO momentarily. Higher utilization increases the likeliness of IO queuing. Always consider this metric along with response time and IO queue depth.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 * (\r\n  1 - (\r\n    node_filesystem_avail_bytes{fstype!~\"tmpfs|overlay\", environment=\"$env\", instance=~\"$instance\"}\r\n    /\r\n    on(instance, device)\r\n    node_filesystem_size_bytes{fstype!~\"tmpfs|overlay\", environment=\"$env\", instance=~\"$instance\"}\r\n  )\r\n)\r\n\r\n",
     "legendFormat": "{{mountpoint}}: {{instance}}"
    }
   ]
  },
  {
   "title": "System Load Average",
   "type": "timeseries",
   "description": "Display Load average ",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - Load 1m"
    },
    {
     "expr": "node_load5{instance=~\"$instance\"}\r\n",
     "legendFormat": "{{instance}} - Load 5m"
    },
    {
     "expr": "node_load15{instance=~\"$instance\"}\r\n",
     "legendFormat": "{{instance}} - Load 15m"
    }
   ]
  },
  {
   "title": "Disk I/O Utilization",
   "type": "timeseries",
   "description": "Shows information about the disk space usage of the specified mountpoint.\n\n**Used** is the amount of space used.\n\n**Free** is the amount of space not in use.\n\n**Used+Free** is the total disk space allocated to the mountpoint.\n\nHaving *Free* close to 0 B is not good because of the risk to have a “disk full” error that can block one of the services or even cause a crash of the entire system.\n\nIn case Free is close to 0 B consider to remove unused files or to expand the space allocated to the mountpoint.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum( rate(node_disk_read_bytes_total{environment=\"$env\", instance=~\"$instance\"}[1m]))",
     "legendFormat": "{{device}} - {{instance}}"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{environment=\"$env\", instance=\"$instance\"}[1m])\r\n",
     "legendFormat": "{{device}} - {{instance}}"
    },
    {
     "expr": "rate(node_disk_reads_completed_total{environment=\"$env\", instance=\"$instance\"}[1m])\r\n",
     "legendFormat": "{{device}} - {{instance}}"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{environment=\"$env\", instance=\"$instance\"}[1m])\r\n",
     "legendFormat": "{{device}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "timeseries",
   "description": "Shows amount of physical IOs (reads and writes) different devices are serving. Spikes in number of IOs served often corresponds to performance problems due to IO subsystem overload.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{environment=\"$env\", instance=~\"$instance\"}[$interval])\r\n+ \r\nrate(node_disk_writes_completed_total{environment=\"$env\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{device}} - {{instance}}"
    }
   ]
  },
  { "title": "Cluster Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Mongodb Uptime",
   "type": "stat",
   "description": "Mongodb Service Uptime in hours",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": " mongodb_instance_uptime_seconds{environment=~\"$env\",instance=~\"$instance\"} ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "gauge",
   "description": "The number of active client connections to the server. Active client connections refers to client connections that currently have operations in progress.",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_connections{environment=\"$env\", instance=~\"$instance\", state=\"active\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Created Connections",
   "type": "gauge",
   "description": "Count of all incoming connections created to the server. This number includes connections that have since closed.",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_connections{environment=\"$env\", instance=~\"$instance\", state=\"totalCreated\"}\r\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Available Connections",
   "type": "gauge",
   "description": "The number of unused incoming connections available. Consider this value in combination with the value of connections.current to understand the connection load on the database, and the UNIX ulimit Settings document for more information about system thresholds on available connections.",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_connections{environment=\"$env\", instance=~\"$instance\", state=\"available\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connections / Sec",
   "type": "gauge",
   "description": "The number of incoming connections from clients to the database server. This number includes the current shell session. Consider the value of connections.available to add more context to this datum.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(mongodb_connections{environment=\"$env\", instance=~\"$instance\", state=\"totalCreated\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "opcounters",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 44 },
   "options": {
    "content": "A document that reports on database operations by type since the mongod instance last started. These numbers will grow over time until next restart. Analyze these values over time to track database utilization."
   }
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "description": "MongoDB Connections",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": " mongodb_connections{environment=\"$env\", instance=~\"$instance\", state=~\"active|available\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Reads & Writes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{environment=\"$env\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} Reads"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{environment=\"$env\", instance=\"$instance\"}[5m])",
     "legendFormat": "{{instance}} Writes"
    }
   ]
  },
  {
   "title": "Query Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_total{environment=\"$env\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Size of Database",
   "type": "stat",
   "description": "MongoDB  database Size",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum without(cl_id, rs_nm, rs_state, instance) ( mongodb_dbstats_storageSize{environment=\"$env\", instance=~\"$instance\"})",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "TOP 10 Databases by Growth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(10, sum by (database) (mongodb_collstats_storageStats_totalSize{rs_state=\"1\"})) >0",
     "legendFormat": "{{environment}} - {{database}} "
    }
   ]
  },
  {
   "title": "TOP 10 Databases by Growth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(10, rate(mongodb_mongod_db_data_size_bytes[5m]))",
     "legendFormat": "{{environment}} - {{database}} "
    }
   ]
  },
  {
   "title": "TOP 10 Collections by Growth",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "\r\ntopk(10,\r\n  rate(\r\n    mongodb_collstats_storageStats_totalSize{\r\n      rs_state=\"1\",\r\n      database=~\"$database\",\r\n      collection=~\"$collection\"\r\n    }[15m]\r\n  ) > 0\r\n)\r\n",
     "legendFormat": "{{database}}.{{collection}} - {{instance}}"
    }
   ]
  },
  {
   "title": "TOP 10 Collections by Size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(10, mongodb_collstats_storageStats_totalSize{rs_state=\"1\",database=~\"$database\",\r\n      collection=~\"$collection\"})\r\n\r\n",
     "legendFormat": "{{database}}.{{collection}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Top Hottest Collections by Read",
   "type": "timeseries",
   "description": "Show the 5 collections that are most frequently read.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(5, sum(rate(mongodb_top_readLock_count{environment=~\"$env\", instance=~\"$instance\",database=~\"$database\"}[5m])) by (collection, database, rs_nm))",
     "legendFormat": "{{database}}.{{collection}}"
    }
   ]
  },
  {
   "title": "Top Hottest Collections by Write",
   "type": "timeseries",
   "description": "Show the 5 collections that are most frequently read.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(5, sum(rate(mongodb_top_writeLock_count{environment=~\"$env\", instance=~\"$instance\",database=~\"$database\"}[5m])) by (collection, database, rs_nm))",
     "legendFormat": "{{database}}.{{collection}}"
    }
   ]
  },
  {
   "title": "Number of Collections /DB",
   "type": "bargauge",
   "description": "MongoDB stores documents in collections. Collections are analogous to tables in relational databases.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 111 },
   "targets": [
    {
     "expr": "topk(10, sum without(cl_id, rs_nm, rs_state, instance) (mongodb_dbstats_collections{environment=\"$env\", instance=~\"$instance\",database=\"$database\"})) ",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Total Indexs/DB",
   "type": "stat",
   "description": "Total number of indexes across all collections in the database.",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 121 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,sum(mongodb_mongod_db_indexes_total{environment=~\"$env\", instance=~\"$instance\",database=~\"$database\"}) by (database, collection))",
     "legendFormat": "{{database}}.{{collection}}"
    }
   ]
  },
  { "title": "Replication Set Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 124 } },
  {
   "title": "Replication State",
   "type": "stat",
   "description": "MongoDB replication lag occurs when the secondary node cannot replicate data fast enough to keep up with the rate that data is being written to the primary node. It could be caused by something as simple as network latency, packet loss within your network, or a routing issue.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 125 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max_over_time(\r\n  mongodb_members_state{member_state=~\"PRIMARY|SECONDARY\", environment=~\"$env\", instance=~\"$instance\"}[5m]\r\n)\r\n",
     "legendFormat": "||{{member_state}} ||  {{member_idx}}  "
    }
   ]
  },
  {
   "title": "Replication Lag",
   "type": "timeseries",
   "description": "This shows the time since the last election.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 125 },
   "targets": [
    {
     "expr": "mongodb_mongod_replset_member_replication_lag{environment=~\"$env\",instance=~\"$instance\"}",
     "legendFormat": "{{name}}    :  {{state}}"
    }
   ]
  }
 ]
}